version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    command: postgres -c log_statement=all
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - data-volume:/var/lib/postgresql/data
      - data-volume:/var/log

  migration:
    image: flyway/flyway
    volumes:
      - ./database/migration/schema:/flyway/sql
    depends_on:
      - db

  adminer:
    image: adminer:4.8.1
    restart: always
    environment:
      ADMINER_DESIGN: nette
    ports:
      - 6002:8080
    depends_on:
      - db

  api:
    build:
      context: ./backend
    command: reflex -r '\.go$$' -s -- sh -c 'go run cmd/api/main.go -databaseDatasource="${DATABASE_DATASOURCE}" -serviceAccountKeyPath=/tmp/serviceAccount.json -port=1991'
    ports:
      - 8888:8888
    volumes:
      - ./backend:/app
    working_dir: /app

  frontend:
    build: 
      context: ./frontend
    ports:
      - 80:80

volumes:
  data-volume:
  node_modules:
