version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    command: postgres -c log_statement=all
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USEDR:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-p@ssw0rd}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - data-volume:/var/lib/postgresql/data
      - data-volume:/var/log

  migration:
    image: flyway/flyway
    volumes:
      - ./database/migration/sql:/flyway/sql
    depends_on:
      - db

  backend:
    build:
      context: ./backend
      args:
        - UID=${UID}
        - GID=${GID}
        - UNAME=${UNAME}
    command: reflex -r '\.go$$' -s -- sh -c 'go run cmd/api/main.go'
    volumes:
      - ./backend:/app
      - lets_encrypt_cert_cache:/var/www/.cache
    environment:
      PORT: "8888"
    ports:
      - 8888:8888

  frontend:
    build:
      context: ./frontend
    ports:
      - 4200:4200
    
  adminer:
    image: adminer:4.8.1
    restart: always
    environment:
      ADMINER_DESIGN: nette
    ports:
      - 6002:8080
    depends_on:
      - db

volumes:
  data-volume:
  node_modules:
  lets_encrypt_cert_cache: 
