FROM golang:1.17.6 AS installer-reflex
RUN go install github.com/cespare/reflex@latest


FROM golang:1.17.6
COPY --from=installer-reflex /go/bin/reflex /go/bin/reflex 

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

CMD [ "reflex", "-h" ]